### ISSUE TITLE
WTFcsv - Upload/Link - If a column has more than 5 items, it shows up blank

### ISSUE THREAD

**Issue by esalling23** [c4fcm/DataBasic#10]
![screen shot 2015-10-22 at 2 08 20 pm](https://cloud.githubusercontent.com/assets/11821504/10674188/ab70c90c-78c7-11e5-82ab-756d181cd7b3.png)
![screen shot 2015-10-22 at 2 17 07 pm](https://cloud.githubusercontent.com/assets/11821504/10674199/b07521b4-78c7-11e5-8d4e-c321c2310a7e.png)

**Comment by jayvachon** [comment]
this cap is configured in wtfcsvstat.py. when there are > 5 values, the app tries to display a summary of the values (which looks to be working with numbers, but not with text)

**Comment by jayvachon** [comment]
values are only shown if not all strings are unique
