### ISSUE TITLE
Data recognized as date, displays incorrect values

### ISSUE THREAD

**Issue by mattwbenson** [c4fcm/DataBasic#102]
![capture](https://cloud.githubusercontent.com/assets/12397944/11661091/2882d50c-9d9e-11e5-876f-86b8a38d6259.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12397944/11661093/297b1dac-9d9e-11e5-891d-ef0803e77593.PNG)

The original sheet had the data written in the form of Jan-15, Dec-15, etc, or December 24-30, December 3-9, etc.

**Comment by jayvachon** [comment]
https://github.com/c4fcm/DataBasic/issues/88
