### ISSUE TITLE
fails to link to google spreadsheets, throws CannotSendRequest

### ISSUE THREAD

**Issue by mattwbenson** [c4fcm/DataBasic#103]
![capture](https://cloud.githubusercontent.com/assets/12397944/11661372/a9efdb2a-9d9f-11e5-9b0b-d4422c9c7b41.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12397944/11661375/aab23a26-9d9f-11e5-87bf-0f6cf164b433.PNG)

**Comment by jayvachon** [comment]
need more info on this one

**Comment by jayvachon** [comment]
actually - just reopen if issue re-arises
