### ISSUE TITLE
WTFcsv linking to Google Sheets throws socket error

### ISSUE THREAD

**Issue by mattwbenson** [c4fcm/DataBasic#114]
![capture](https://cloud.githubusercontent.com/assets/12397944/11688949/877c0d3e-9e5d-11e5-92d6-f9dcfd445dd0.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12397944/11688950/88b72904-9e5d-11e5-9a69-4ddecca6f5cf.PNG)

**Comment by kanarinka** [comment]
Can you provide the link you were using so we can test against that?

**Comment by mattwbenson** [comment]
https://docs.google.com/spreadsheets/d/13BrQ6CuuAuEaeIlopJ8Bu102bKrxz_C90K0jv2ygoME/edit?usp=sharing

**Comment by jayvachon** [comment]
problem here was empty csv sheets ~ handling this now
