### ISSUE TITLE
This Gutenberg link causes a UnicodeEncodeError

### ISSUE THREAD

**Issue by mattwbenson** [c4fcm/DataBasic#117]
http://www.gutenberg.org/files/50651/50651-h/50651-h.htm

![capture](https://cloud.githubusercontent.com/assets/12397944/11692950/3a0448d8-9e70-11e5-86eb-bf640ee78bed.PNG)

**Comment by jayvachon** [comment]
https://github.com/c4fcm/DataBasic/issues/120
