### ISSUE TITLE
WTFcsv: file throws error

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#135]
this spreadsheet linked https://docs.google.com/spreadsheets/d/1wBQGIGDOXjSXCGHPKcPPXMNPx-fmspxr0TJ7f4eFL9Q/edit#gid=1529900512

 throws the attached error

![screencapture-localhost-5000-en-wtfcsv-1449869199624](https://cloud.githubusercontent.com/assets/1102550/11755941/1187c8b6-a024-11e5-9417-e31cf940e217.png)

**Comment by jayvachon** [comment]
this sheet seems to be working for me now (it wasn't when I first tried it out) - could you give it another shot at let me know if you're still getting the exception?

**Comment by kanarinka** [comment]
interesting - seems fixed! go team!

**Comment by jayvachon** [comment]
wonderful/magical!
