### ISSUE TITLE
WTFcsv: multi worksheet link throws error

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#136]
Using this spreadsheet https://docs.google.com/spreadsheets/d/1Ec5lWUENFsT7SZSNLb6g9xzVhb2SZ19ADfIyCR9wlMQ/edit#gid=1419190237

I get an IndexError when I try to access the Contact or Demographics worksheets. See screentshot

![screencapture-localhost-5000-en-wtfcsv-results-566b4083e1cffc3f34b7ffca-sheets-2-1449869566528](https://cloud.githubusercontent.com/assets/1102550/11756033/de7804bc-a024-11e5-979b-07cac5a729f2.png)

**Comment by jayvachon** [comment]
this was actually a problem with the 'what's next' section looking for a random column and not finding one with a most frequent value. all set now.
