### ISSUE TITLE
WTFcsv: weirdly formatted data throws indexerror

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#137]
Data that is not in a standard columns & rows format throws an IndexError. For example, this spreadsheet:
https://docs.google.com/spreadsheets/d/1RetBXVEUDrrSdmbbl8ObkjJDDgk0IYSNbaUT1hnQptQ/edit?usp=sharing 

I think we need some nice web feedback that says: "We can't analyze that data because it's not in a standard form. Your first row should contain the names of your columns."

This is a teaching moment - my students often have tried to analyze data that is in a weird format, doesn't have column headers, etc. And most software can't deal with it. So we can teach them

**Comment by jayvachon** [comment]
wtfcsv now checks for columns named "_unnamed" which is what csvkit returns when it finds an empty column.
