### ISSUE TITLE
WordCounter: error

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#140]
When inputting this link: http://www.bartleby.com/124/pres13.html 

I get an attribute error (attached)
![screencapture-localhost-5000-en-wordcounter-1449949343270](https://cloud.githubusercontent.com/assets/1102550/11763576/9c7b126a-a0de-11e5-983a-61acdadf27b5.png)

**Comment by jayvachon** [comment]
dang this is an old site - no paragraph tags. I'll see about making it more flexible
