### ISSUE TITLE
Adding videos to tool pages

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#151]
These appear below tools in a banded (white) row similar to the "What do I do next?" on the results page.

2 columns:
Video column says "About Toolname"

Activity column says "Are you an Educator? Try our Activity Guide"
"DataBasic activities are suitable for classes and workshops for participants from middle school thru higher ed. No prior data experience necessary!"

Has 2 buttons and screenshot of guide. See picture

**Comment by jayvachon** [comment]
oh wait - so you mean remove the current video button and move it to this new section?

**Comment by kanarinka** [comment]
[Scan Dec 18, 2015, 11.57 AM.pdf](https://github.com/c4fcm/DataBasic/files/66908/Scan.Dec.18.2015.11.57.AM.pdf)

**Comment by jayvachon** [comment]
k - did my best with the styling but let me know if you have any ideas for changes
