### ISSUE TITLE
parsing errors (LOG ALL OF THEM HERE)

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#16]
It seems there are a number of aspects of csvs that might hinder our csvkit from being able to read them. Let's log all of them in this issue.

**Comment by kanarinka** [comment]
This spreadsheet breaks on H27: '408 S Huntington Ave.' - maybe the period at the end of the cell??

**Comment by jayvachon** [comment]
a column can't have cells with dates and cells with times (all cells must be datetimes, dates, or times)

**Comment by kanarinka** [comment]
Weird on this Titanic survivors file - WTFcsv doesn't break but it thinks everything is a column
[titanic.csv.txt](https://github.com/c4fcm/DataBasic/files/31126/titanic.csv.txt)

**Comment by jayvachon** [comment]
that's a txt file!

**Comment by kanarinka** [comment]
sorry yes - just rename to CSV. However, I actually fixed this particular
bug so we can eliminate this particular comment

**Comment by jayvachon** [comment]
> This spreadsheet breaks on H27: '408 S Huntington Ave.' - maybe the period at the end of the cell??
https://docs.google.com/spreadsheets/d/1Ec5lWUENFsT7SZSNLb6g9xzVhb2SZ19ADfIyCR9wlMQ/edit#gid=0 

this spreadsheet was breaking because there's a column w/o a header in sheet 3. we're handling that now, and if I remove the column then I'm able to get results so I think this is good
