### ISSUE TITLE
WTFcsv: results page text changes

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#18]
- Instead of 'This is column number 1' I think we should just say 'Column #1'
- Can we say the following for data types: unicode --> "text", datetime --> "dates and times", int, float, etc --> "numbers"
- If column has datetime type data, let's say "The earliest date is..." instead of "The smallest number is"
- Likewise for "The latest date is..."
- When we say "The most frequent values in this column are", can we show the count of those values next to the value text e.g. "Red (37)"

Maybe try to do this for tomorrow 11/10 since most of it's easy? If hard or timeconsuming, then can be postponed.

**Comment by jayvachon** [comment]
got all of these in except the last one - i'll revisit if i have time
