### ISSUE TITLE
Remove "fakepath" from file input

### ISSUE THREAD

**Issue by jayvachon** [c4fcm/DataBasic#187]
After selecting a file to upload, the field displays a path that begins `c:\fakepath\`. The file doesn't process on submit

<img width="639" alt="screen shot 2016-01-27 at 5 26 36 pm" src="https://cloud.githubusercontent.com/assets/6832921/12630563/0b02ae90-c51b-11e5-9660-476cf12fe2cd.png">

**Comment by kanarinka** [comment]
FYI the fakepath thing is not related to the bug - the bug was related to the file not being in UTF-8 encoding. But we should still remove the "c:\fakepath" thing because it's a little weird

**Comment by jayvachon** [comment]
are either of you still seeing this? It's not happening for me anymore (locally or on the server)

**Comment by kanarinka** [comment]
I see it - it shows up after you select your file for uploading

[image: Screenshot 2016-02-23 12.34.37.png]

**Comment by jayvachon** [comment]
oh interesting - it doesn't happen in firefox

**Comment by kanarinka** [comment]
I'm using Chrome. I tried fixing this a couple weeks ago and it seems like
it's the default browser behavior for some browsers. If it seems like a
time-sink this is not that high priority for fixing. We can live with
"fakepath" I just think it's really silly default behavior because it's
disconcerting to the user.

**Comment by jayvachon** [comment]
yeah - wow, I'm going to have to set this one aside for now. even if I call setTimeout every 100ms to remove the text, chrome still adds it in. it looks like this is happening because of the way we've combined the input field with the button: http://meta.stackexchange.com/a/96844

also this is apparently intentional and something that all browsers will eventually be doing for security reasons. might be better to approach this input field in a different way, unless we want to leave it be

**Comment by kanarinka** [comment]
Yeah, just leave it if it's not fast - it's mildly annoying but not a
showstopper

**Comment by jayvachon** [comment]
ok fixed this --- was a dumb mistake on my part B)
