### ISSUE TITLE
Testing WordCounter locally with 16MB text file gives error 

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#195]
![image](https://cloud.githubusercontent.com/assets/1102550/12983889/55d3ddaa-d0b9-11e5-9acf-3d1b167c7f85.png)

The file is here: 
https://www.dropbox.com/s/dsx4fubcxy4xt6a/22kAmazonGameReview.rtf?dl=0

**Comment by kanarinka** [comment]
This might be related to #194

**Comment by jayvachon** [comment]
is this an encoding issue?

**Comment by kanarinka** [comment]
Assigning this to rahul and I bc I think it is encoding

**Comment by kanarinka** [comment]
This IS the same as #194 - so not encoding but performance and related to the gunicorn worker timing out
