### ISSUE TITLE
Make sure that file upload supports 100mb

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#196]
is the limit currently 10 or 100mb?

**Comment by jayvachon** [comment]
I believe these are the two places we're setting a limit (both are set to 100mb)
https://github.com/c4fcm/DataBasic/blob/master/databasic/static/js/wtfcsv-validate.js#L4
https://github.com/c4fcm/DataBasic/blob/master/databasic/logic/filehandler.py#L32

**Comment by kanarinka** [comment]
ok i'm closing
