### ISSUE TITLE
Integrate Portuguese stopwords if DB is in Portuguese

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#199]
Can we just use NLTK's built-in Portuguese stopwords?
http://www.nltk.org/howto/portuguese_en.html

**Comment by jayvachon** [comment]
this shouldn't be hard especially if we're already performing a check for spanish
we do already have the Portuguese stopwords (along with a bunch of other languages) here: https://github.com/c4fcm/DataBasic/tree/master/nltk_data/corpora/stopwords

**Comment by kanarinka** [comment]
Sorry - Daniel asked if we could use this set of Portuguese stopwords - how hard is it to integrate these?

**Comment by jayvachon** [comment]
which of those sets does he want us to use? it's really easy to update - you just have to replace this file https://github.com/c4fcm/DataBasic/blob/master/nltk_data/corpora/stopwords/portuguese

**Comment by kanarinka** [comment]
Super thx

**Comment by kanarinka** [comment]
Here's what Daniel says about which to use: 
"For the stopwords I suggest you use the Brazilian portuguese files. It is similar to Portugal portuguese, but I translated to Brazilian portuguese.

You can use Brazilian part and Collection CHAVE. They are complementary, there are some repeated words."

**Comment by kanarinka** [comment]
I integrated the top 100 brasilian words from this link from Daniel for our portguese stopwords.
