### ISSUE TITLE
All tools: Intro text for tomorrow

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#21]
(Rahul feel free to tweak)

Can we change the text at the top of the page to this:

WordCounter:
(BIG) WordCounter analyzes your text and tells you the most common words and phrases.
(smaller) This tool helps you count words, bigrams, and trigrams in plain text. This is often the first step in quantitative text analysis.

WTFcsv: 
(BIG) WTFcsv tells you WTF is going on with your .csv file. 
(smaller) Data arrives at your doorstep in the form of a spreadsheet but how do you find a story in rows and columns? WTFcsv provides the first step by characterizing each column so that you can ask more questions.

SameDiff:
(BIG) SameDiff compares two or more text files and tells you how similar or different they are
(smaller) What distinguishes one candidate from another? One musical artist from another? One constitution from another? SameDiff shows you how similar text files are using cosine similarity and shared words and how different they are using TF-IDF to identify frequent and unique words.

**Comment by jayvachon** [comment]
updated - feel free to reopen with tweaks!
