### ISSUE TITLE
Add Input to Connect the Dots

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#226]
@rahulbot and I are discussing the activity and we'd love to include a copy and paste option so that people can copy from either Google Sheet or Excel doc and use that as input to connect the Dots. This is consistent with WordCounter and SameDiff (where you can just paste text as input).

This feature would parse tab-delimited text (which is how Google Sheets and Excel do the copy) and use that as input to Connect the Dots.

@s2tephen do you think you could work this in?

**Comment by s2tephen** [comment]
Doesn't address the edge case of actual tabs within the data, i.e.
```
"source"\t"target"
"node"\t"node\twith\ttabs"
```
It's pretty low-priority so I'll come back and follow up on this scenario later.
