### ISSUE TITLE
Connect the Dots: hover node effect

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#229]
When you hover on a node in the d3 graph on on the table, can you highlight the edges and nodes that that hovered node is connected to? We feel like this might be a good way to reinforce the idea of "degree". 

Try using the WordCounter red color and see if that looks ok.

**Comment by s2tephen** [comment]
Sure, I'll try it out.

One thing I've seen looking through other network graphing tools is using the opacity to the same effect (by completely hiding or making semi-transparent all the nodes that aren't connected to the currently hovered node), so that's another option as well.

**Comment by s2tephen** [comment]
<img width="1203" alt="Neighborhood hover interaction" src="https://cloud.githubusercontent.com/assets/1381021/17917722/f99ab32a-698c-11e6-85fc-96b3b23b5c1f.png">

### Unresolved issues:
- Tooltip sometimes covers the connected nodes
- What is the intended behavior re: the active (clicked) node?
  - Show the neighborhood of the hovered node but the tooltip of the active node (current)
  - Show the neighborhood of the active node and ignore hovers when a node is active (makes the most sense to me)

**Comment by jpailthorpe** [comment]
I will make this into a new issue to keep things clean in our doc. #236
