### ISSUE TITLE
Clicking on edge of language selector buttons doesn't lead to language being selected

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#230]
It's because the TEXT (en, es, pt) is the thing that is linked but people sometimes click on the BG button. We should fix that prior to the CTD release.

**Comment by kanarinka** [comment]
CRAP this is broken totally in Firefox - I will fix in next cpl of days... sigh...

**Comment by numeroteca** [comment]
It is still broken. I think you just need to change the "button" tag (id="language-selector") by a "div".
