### ISSUE TITLE
Deliver and integrate designed mockups into new homepage 

### ISSUE THREAD

**Issue by jpailthorpe** [c4fcm/DataBasic#235]
- [ ] Mockup for homepage 

Once Stephen gets the mockups, he will be tasked with integrating the new homepage to test/review

**Comment by jpailthorpe** [comment]
@s2tephen did the integration of the new homepage, but I will leave this open until I can verify the images on features

**Comment by s2tephen** [comment]
Closing since everything else is done besides the feature images (see #259).
