### ISSUE TITLE
source images for databasic home page feature sections 

### ISSUE THREAD

**Issue by jpailthorpe** [c4fcm/DataBasic#239]

**Comment by kanarinka** [comment]
How many do we need? And would it be possible to use video stills or are
those not hi-res enough?

**Comment by jpailthorpe** [comment]
I'm going to source a bunch right now and then you can make final decsions. If there are any places where you have pictures or videos aside from the original workshop and the salzburg workshop, let me know! Maybe we have some from BCM?

**Comment by jpailthorpe** [comment]
intial images are in. We can add different ones in the next month or so but we will open that as a new issue
