### ISSUE TITLE
homepage: text underneath tool logos and in each feature should be left aligned, not centered. 

### ISSUE THREAD

**Issue by jpailthorpe** [c4fcm/DataBasic#245]
see mockup!

**Comment by s2tephen** [comment]
Realigned feature text but ended up leaving tool blurbs centered, because I thought they looked super weird left-aligned:
<img width="1206" alt="left-aligned-blurbs" src="https://cloud.githubusercontent.com/assets/1381021/18559629/22eb47b0-7b46-11e6-8f88-f51ddfce3985.png">
