### ISSUE TITLE
Should the table download include community data?

### ISSUE THREAD

**Issue by s2tephen** [c4fcm/DataBasic#277]
Currently, users can see the detected communities via the graph colors, but there's no way for them to get that information out of the graph. Should an extra column be added to the csv download (and maybe a metadata field for the gexf output) with a community ID?

**Comment by kanarinka** [comment]
Good thinking. Yes. But instead of id could it be the color (ideally word
version like "heather blue") of the community in the visualization?

**Comment by s2tephen** [comment]
Yep, I can do this, but I'm not sure what to use as the canonical name for each color (community colors are from [`d3.schemeCategory10`](https://github.com/d3/d3-scale#schemeCategory10) and [`d3.schemeCategory20`](https://github.com/d3/d3-scale#schemeCategory20)). I tried running the colors through a hex => name library but I'm getting obscure names like "Matisse" for #1B659D (blue). Any suggestions? We could also just manually name them.

**Comment by s2tephen** [comment]
Tangential but related, should I include the other metadata (degree, betweenness centrality) in the gexf as well?

**Comment by s2tephen** [comment]
Note: when > 20 communities are identified, the naming scheme is the same as `d3.schemeCategory20` but with a trailing number for each group of 20:
e.g. darkblue0, lightblue0, darkorange0, ... , darkturquoise0, lightturquoise0, darkblue1 (and so on)
