### ISSUE TITLE
Navigation bar for WTFcsv

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#43]
As discussed today - we will add a nav bar on the WTF output page between the text "You have 891 rows..." and the cards.

The bar is 100% width and gets divided into the # of columns in the spreadsheet. It serves as a map of the spreadsheet and also as a way to turn cards' visibility on/off.

- only shows up if more than 6 or so columns
- on rollover of each little square, will show column name and maybe shows icon of data type
- should be a fixed nav-y thing so when you scroll it stays on page
- should have "show all" and "show none" option (can get aidan's help later)
- clicking on nav box that corresponds to that column will show/hide cards
- each big card gets an X to hide it and the nav box that corresponds to it will grey out
- on mouseover of big card then the nav box that corresponds to that column is highlighted in red or appropriate color or dark yellow (consult Aidan)

**Comment by jayvachon** [comment]
got a basic version of this working -- it's a little confusing w/o animation, but I'd like to get opinions on it before going forward

**Comment by kanarinka** [comment]
Yes - agreed on it being a little confusing. Could we try the following to see if it helps:
- if mouse is hovering on a large card, add red border to the large card so that it's visually connected to the red square of the nav bar
- cursor turns into hand when it mouses over an X on the large card
- cursor turns into hand when it mouses over anything on the nav bar
- if a square on the navbar is greyed out it doesn't turn red on hover, just stays grey
- when user clicks the navbar to turn a square from yellow to grey, then the red goes away and it's just grey
- the last square in the navbar that you click on has the tooltip remain there - could you make it go away on mouseout, i.e. once the mouse has left the square?

**Comment by jayvachon** [comment]
^ made these changes. I'll leave this open for the time being tho

**Comment by jayvachon** [comment]
feature removed
