### ISSUE TITLE
WordCounter - color shifts intentional?

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#56]
the red color shifts on the input vs the output page - is that intended? Seems like we should keep the same colors? Or maybe check w Aidan

**Comment by jayvachon** [comment]
![wordcounter_output1](https://cloud.githubusercontent.com/assets/6832921/11351069/8c46b092-9202-11e5-8443-52798af222b6.png)
i'm going off this design (which is pretty old at this point - either way, not hard to play around with the colors)

**Comment by kanarinka** [comment]
Let's mark this one for consulting with Aidan to see what she thinks. And
do we want to add back in the cloud bg? I kinda like it!

**Comment by jayvachon** [comment]
i like it too! but i never got the image :(
(which actually might be my fault because I don't think i gave aidan the image dimensions)\
