### ISSUE TITLE
databasic logo on tool pages

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#65]
should be all white and aligned to the right

Jay - do you have the .PSD for the logo?

**Comment by jayvachon** [comment]
not yet but it'll be easy to replace once i do

**Comment by kanarinka** [comment]
When you get it can you email me a copy? Will be helpful to have on hand
for other promo materials too.

**Comment by jayvachon** [comment]
got a png. i'll post the psd to the slack channel once i get it
