### ISSUE TITLE
WordCounter: what to do next 

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#97]
Test case: Beyonce's lyrics

Right now the what next text chooses "i'm" as the top word but I'm doesn't occur in any of the bigrams or trigrams. We should verify that the top word occurs in at least one of the bigrams and one of the trigrams and if not then go down the list to the next word.

Also, if a word occurs once it should say "1 use" instead of "1 uses"

**Comment by jayvachon** [comment]
all set - defaulting to the most popular word if no popular words exist in both bigrams & trigrams (pretty unlikely)
